name: tts_mod_vault
description: "Download and backup assets for your Tabletop Simulator mods."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.3.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_archive: ^6.0.3
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  http: ^1.2.2
  dio: ^5.7.0
  collection: ^1.19.0
  window_manager: ^0.4.3
  mime: ^2.0.0
  file_picker: ^9.2.3
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
