name: tts_mod_vault
description: "Download and backup assets for your Tabletop Simulator mods"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path: ^1.9.0
  hooks_riverpod: 2.6.1
  flutter_hooks: ^0.21.2
  http: ^1.2.2
  dio: ^5.7.0
  collection: ^1.19.0
  window_manager: ^0.5.1
  mime: ^2.0.0
  file_picker: ^10.1.9
  archive: ^4.0.5
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  hive_ce_flutter: ^2.3.1
  open_filex: ^4.7.0
  image: ^4.5.4
  bson: ^5.0.7
  fixnum: ^1.1.1
  pdfrx_engine: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.1

icons_launcher:
  image_path: "assets/icon/tts_mod_vault_icon.png"
  platforms:
    windows:
      enable: true
    macos:
      enable: true
    linux:
      enable: false

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/icon/
