name: tts_mod_vault
description: "Download and backup assets for your Tabletop Simulator mods"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.3.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_archive: ^6.0.3
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  http: ^1.2.2
  dio: ^5.7.0
  collection: ^1.19.0
  window_manager: ^0.5.1
  mime: ^2.0.0
  file_picker: ^10.1.9
  archive: ^4.0.5
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  open_filex: ^4.7.0
  image: ^4.5.4
  bson: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  hive_ce_generator: ^1.9.2
  build_runner: ^2.5.3

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/tts_mod_vault_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/tts_mod_vault_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/icon/
