enum ContextMenuActionEnum {
  openImagesViewer,
  openInExplorer,
  openInBrowser,
  openSteamWorkshopPage,
  openBackupInExplorer,
  openFile,
  copyUrl,
  copyFilename,
  copySaveName,
  copyBackupFilename,
  download,
  deleteBackup,
  replaceUrl,
  updateMod,
}
